services:
  - type: web
    name: saadhya
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: SECRET_KEY
        generateValue: true
